export const FETCH_ADDNEWPOLL_REQUEST = 'FETCH_ADDNEWPOLL_REQUEST';

export const FETCH_ADDNEWPOLL_SUCCESS = 'FETCH_ADDNEWPOLL_SUCCESS';

export const FETCH_ADDNEWPOLL_ERROR = 'FETCH_ADDNEWPOLL_ERROR';

console.log("ADDNEWPOLL.type.js running");