export const FETCH_LISTOFUSERS_REQUEST = 'FETCH_LISTOFUSERS_REQUEST';

export const FETCH_LISTOFUSERS_SUCCESS = 'FETCH_LISTOFUSERS_SUCCESS';

export const FETCH_LISTOFUSERS_ERROR = 'FETCH_LISTOFUSERS_ERROR';

console.log("LISTOFUSERSValidation.type.js running");