export const FETCH_LISTALLPOLLS_REQUEST = 'FETCH_LISTALLPOLLS_REQUEST';

export const FETCH_LISTALLPOLLS_SUCCESS = 'FETCH_LISTALLPOLLS_SUCCESS';

export const FETCH_LISTALLPOLLS_ERROR = 'FETCH_LISTALLPOLLS_ERROR';

console.log("LISTALLPOLLS.type.js running");