export const FETCH_REGISTRATION_REQUEST = 'FETCH_REGISTRATION_REQUEST';

export const FETCH_REGISTRATION_SUCCESS = 'FETCH_REGISTRATION_SUCCESS';

export const FETCH_REGISTRATION_ERROR = 'FETCH_REGISTRATION_ERROR';

console.log("registration.type.js running");